name: Deploy Functions

on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
    make-migrations:
        runs-on: ubuntu-latest

        env:
            SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
            PROJECT_ID: ${{ secrets.PROJECT_ID }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        steps:
            - uses: actions/checkout@v3

            - uses: supabase/setup-cli@v1
              with:
                  version: latest

            - run: |
                supabase link --project-ref $PROJECT_ID
                supabase db push -p $DB_PASSWORD